name: diagnose-failed-workflow

description: "Run ADK agent to analyze failed GitHub Action runs"

author: Joshua Burns

inputs:
  github_token:
    description: "GitHub token with repo scope"
    required: true
  llm_model:
    description: "Model ID understood by LiteLLM (e.g., openai/gpt-4o, anthropic/claude-3-sonnet)"
    default: "openai/gpt-4o"
  image:
    description: "Debugger container image"
    default: "ghcr.io/jburns24/failed-workflow-debugger-agent:latest"
  run_id:
    description: "Workflow run ID to diagnose (default: triggering run)"
    required: false

branding:
  icon: "activity"
  color: "purple"

runs:
  using: "composite"
  

  
  steps:
  - name: Download workflow logs
    shell: bash
    env:
      GH_TOKEN: ${{ inputs.github_token }}
      INPUT_RUN_ID: ${{ inputs.run_id }}
      FALLBACK_ID: ${{ github.event.workflow_run.id }}
      GITHUB_RUN_ID: ${{ github.run_id }}
    id: download_logs
    run: |
      echo "::add-mask::$GH_TOKEN"
      # Ensure gh is authenticated (store token in keychain for this run)
      gh auth status || echo "$GH_TOKEN" | gh auth login --with-token

      RID=${INPUT_RUN_ID:-${FALLBACK_ID:-$GITHUB_RUN_ID}}
      echo "📥 Fetching logs for run $RID ..."
      if ! gh api "/repos/${{ github.repository }}/actions/runs/$RID/logs" > /tmp/logs.zip; then
        echo "❌ Error: Failed to download workflow run logs for run $RID." >&2
        exit 1
      fi
      echo "log_path=/tmp/logs.zip" >> "$GITHUB_OUTPUT"

  - name: Run LLM debugger container
    shell: bash
    env:
      IMAGE: ${{ inputs.image }}
      OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
      LLM_MODEL: ${{ inputs.llm_model }}
      LOG_PATH: ${{ steps.download_logs.outputs.log_path }}
    run: |
      docker run --rm \
        -e OPENAI_API_KEY \
        -e LLM_MODEL \
        -v "$LOG_PATH:/tmp/logs.zip" \
        "$IMAGE" /app/main.py /tmp/logs.zip > report.md

  - name: Add diagnosis to workflow summary
    shell: bash
    run: |
      echo "### Workflow Diagnosis Report" >> "$GITHUB_STEP_SUMMARY"
      cat report.md >> "$GITHUB_STEP_SUMMARY"
