name: diagnose-failed-workflow

description: "Run ADK agent to analyze failed GitHub Action runs"

author: Windsurf Cascade

inputs:
  github_token:
    description: "GitHub token with repo scope"
    required: true
  llm_model:
    description: "Model ID understood by LiteLLM (e.g., openai/gpt-4o, anthropic/claude-3-sonnet)"
    default: "openai/gpt-4o"
  image:
    description: "Debugger container image"
    default: "ghcr.io/${{ github.repository_owner }}/fw-debugger:latest"
  run_id:
    description: "Workflow run ID to diagnose (default: triggering run)"
    required: false

branding:
  icon: "activity"
  color: "purple"

runs:
  using: "composite"
  

  
  steps:
  - name: Download workflow logs
    shell: bash
    env:
      GH_TOKEN: ${{ inputs.github_token }}
      INPUT_RUN_ID: ${{ inputs.run_id }}
      FALLBACK_ID: ${{ github.event.workflow_run.id }}
      GITHUB_RUN_ID: ${{ github.run_id }}
    id: download_logs
    run: |
      RID=${INPUT_RUN_ID:-${FALLBACK_ID:-$GITHUB_RUN_ID}}
      echo "Fetching run metadata to locate logs URL"
      LOGS_URL=$(gh api "/repos/${{ github.repository }}/actions/runs/$RID" -q .logs_url)
      echo "Downloading logs from $LOGS_URL"
      curl -Ls "$LOGS_URL" -o /tmp/logs.zip
      echo "::set-output name=log_path::/tmp/logs.zip"

  - name: Run LLM debugger container
    shell: bash
    env:
      IMAGE: ${{ inputs.image }}
      OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
      LLM_MODEL: ${{ inputs.llm_model }}
      LOG_PATH: ${{ steps.download_logs.outputs.log_path }}
    run: |
      docker run --rm \
        -e OPENAI_API_KEY \
        -e LLM_MODEL \
        -v "$LOG_PATH:/tmp/logs.zip" \
        "$IMAGE" /app/main.py /tmp/logs.zip > report.md

  - name: Post diagnosis comment
    shell: bash
    env:
      GH_TOKEN: ${{ inputs.github_token }}
    run: |
      function post_comment() {
        local endpoint="$1"
        gh api -X POST -H "Content-Type: application/json" "$endpoint" -f body="$(cat report.md)"
      }

      if [ -n "${{ github.event.workflow_run.pull_requests[0].number }}" ]; then
        pr=${{ github.event.workflow_run.pull_requests[0].number }}
        post_comment "/repos/${{ github.repository }}/issues/${pr}/comments"
      else
        sha=${{ github.event.workflow_run.head_sha }}
        post_comment "/repos/${{ github.repository }}/commits/${sha}/comments"
      fi
