name: diagnose-failed-workflow

description: "Run ADK agent to analyze failed GitHub Action runs"

author: Windsurf Cascade

inputs:
  github_token:
    description: "GitHub token with repo scope"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: "/bin/sh"
  args:
    - -c
    - |
      set -e
      gh auth login --with-token <<< "${{ inputs.github_token }}"
      gh api /repos/${{ GITHUB_REPOSITORY }}/actions/runs/${{ GITHUB_RUN_ID }}/logs --output /tmp/logs.tar.gz
      python -m failed_workflow_debugger_agent.main /tmp/logs.tar.gz > report.md
      # Post comment to PR if exists, else to commit
      if [ -n "${{ github.event.workflow_run.pull_requests[0].number }}" ]; then
        pr=${{ github.event.workflow_run.pull_requests[0].number }}
        gh api \
          -X POST \
          -H "Content-Type: application/json" \
          "/repos/${{ GITHUB_REPOSITORY }}/issues/${pr}/comments" \
          -f body="$(cat report.md)"
      else
        sha=${{ github.event.workflow_run.head_sha }}
        gh api \
          -X POST \
          -H "Content-Type: application/json" \
          "/repos/${{ GITHUB_REPOSITORY }}/commits/${sha}/comments" \
          -f body="$(cat report.md)"
      fi
