name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write
  id-token: write

jobs:
  tag-release:
    name: tag-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: jburns24/failed-workflow-debugger-agent # Where to look for the trust policy <org>/<repo> (octo-sts must be installed on this repo)
          identity: push-tag # prefix of the trust policy expected to be at <scope>/.github/chainguard/<identity>.sts.yaml

      - name: Tag release
        id: push_tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ steps.octo-sts.outputs.token }}
